kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: cT8nLdm2ojTi1C6Qz/uqf/QS7R9ByvG/VR7yUJpgXXs=
      - identity: {}
